FROM flwr/superexec:1.26.1

USER root
RUN apt-get update \
	&& apt-get -y --no-install-recommends install \
	build-essential \
	&& rm -rf /var/lib/apt/lists/*

USER app

WORKDIR /app
COPY --chown=app:app pyproject.toml README.md LICENSE ./
RUN sed -i 's/.*flwr[simulation].*//' pyproject.toml \
    && python -m pip install -U --no-cache-dir .

ENTRYPOINT ["flower-superexec"]